name: API Automation

on:
  push:
  pull_request:

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v4


      - name: Install Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.13"


      - name: Install Dependencies

        run: |

          pip install -r requirements.txt


      - name: Run API Tests

        run: |

          pytest -m api -v


      - name: Run Contract Tests

        run: |

          pytest -m contract -v


      - name: Run DB Tests

        run: |

          pytest -m db -v